### ISSUE TITLE
There is no `Shlomif_Common` file

### ISSUE THREAD

**Issue by mark-in** [thewml/wml-flawed-import#1]
An output of  the `cmake`:

 `CMake Error at CMakeLists.txt:6 (INCLUDE): `
`include could not find load file:`
`Shlomif_Common`
`CMake Error at CMakeLists.txt:8 (SHLOMIF_COMMON_SETUP):`
`Unknown CMake command "SHLOMIF_COMMON_SETUP".`

**Comment by shlomif** [comment]
Hi @mark-in ,

I added a note about how to get the missing file here - https://bitbucket.org/shlomif/website-meta-language/commits/ec309cac71232425bfe3d1ab7d219e764d17b595 .

Otherwise, I don't understand why you created the "thewml" GitHub organisation without consulting me, and then invited me. Website Meta Language is already maintained here - https://bitbucket.org/shlomif/website-meta-language/overview .

**Comment by mark-in** [comment]
Hi @shlomif!
> I added a note about how to get the missing file here - https://bitbucket.org/shlomif/website-meta-language/commits/ec309cac71232425bfe3d1ab7d219e764d17b595 .

Thanks! Maybe it should be included into the WML repo as subproject instead of adding it manually each time?
After adding `Shlomif_Common.cmake` file there is another problem:
 `cmake` complains that
`LIB_INSTALL_DIR must be defined.  Specify it with -DLIB_INSTALL_DIR=...` .
How it should be fixed properly?

> Otherwise, I don't understand why you created the "thewml" GitHub organisation without consulting me, and then invited me. Website Meta Language is already maintained here - https://bitbucket.org/shlomif/website-meta-language/overview . 

I'm really sorry for not consulting with you first.
First of all I found only Debian packages for the WML but I can't install them on my Gentoo machine (they are `.deb`) and I need to build WML from source. Then I found original `http://thewml.org/` website that looks unmaintained, has broken links and so on. Next point was much harder to reach. Accidentally I found your site and just one link to your BitBucket project.

Unfortunately it is a `Mercurical` project - for me and other people it is much easier to use `Git` and therefore easier to contribute. For the first time I've moved your code to `Git` repo and mirrored the website just for me. Then I thought that it is worth to save all of this in one place - on the GitHub. When I imported code GitHub said that there is a GitHub user @shlomif and it suprised me a little :-). Next I invited you because you are here and you are a maintainer.

I just want this project to be a bit easier to find and to be more available.
Anyway, you are the owner of this organization and you can do with it whatever you want.

Sorry again.

**Comment by shlomif** [comment]
You need to specify -DLIB_INSTALL_DIR=lib or -DLIB_INSTALL_DIR=lib64 if I remember correctly. I'll consider adding a sub-project to the repository to facilitate it. Thanks for sharing the history for your motivation regarding setting up the "thewml" project. Perhaps moving the WML sources to GitHub is a good idea due to its popularity.

**Comment by mark-in** [comment]
Yes, it works!
For example `cmake ../wml/src -DLIB_INSTALL_DIR=lib64`
